version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daily"
